config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions'
  }

  root 'home#index'

  get 'menu', to: 'home#menu'

  namespace :admin do
    # root 'dashboard#index'
    get '/' => 'notices#show', as: :root

    resource :notice do
    end

    resources :dishes do
      member do
        put :update_position
      end
    end
    
    resources :dish_groups do
      member do
        put :update_position
      end
    end

    get 'dashboard/edit_background_images', to: 'dashboard#edit_background_images', as: :edit_background_images
    post 'dashboard/edit_background_images', to: 'dashboard#edit_background_images'
    delete 'dashboard/remove_background_image', to: 'dashboard#remove_background_image', as: :remove_background_image
  end
end

app/views/shared/admin/_footer.html.erb
<footer class="main-footer">
  <strong>Copyright © 2025</strong>
  All rights reserved.
</footer>

app/views/shared/admin/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
    <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
    $(document).Toasts('create', {
      delay: 7000,
      autohide: true,
      class: 'bg-<%= type %>',
      title: '<%= type %>',
      body: '<%= value %>',
    })
    <% end %>
  </script>
<% end %>

app/views/shared/admin/_navbar.html.erb
<nav class="main-header navbar navbar-expand navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
    </li>
    <!-- <li class="nav-item dropdown">
      <a class="nav-link bg-info rounded dropdown-toggle" href="#" id="navbarVersionDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        v3.1.0
      </a>
      <div class="dropdown-menu py-0" aria-labelledby="navbarVersionDropdown">
        <a class="dropdown-item bg-info disabled" href="#">v3.1</a>
        <a class="dropdown-item" href="https://adminlte.io/docs/3.0/">v3.0</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="https://adminlte.io/docs/2.4/installation">v2.4</a>
        <a class="dropdown-item" href="https://adminlte.io/themes/AdminLTE/documentation/index.html">&lt;= v2.3</a>
      </div>
    </li> -->
  </ul>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="navbar">

      <!-- Links -->
      <ul class="nav navbar-nav ml-auto">
        <% if admin_user_signed_in? %>
          <li class="nav-item d-none d-md-block">
            <em class="nav-link">Hi, <%= current_admin_user.email %></em>
          </li>
          <li class="nav-item d-none d-md-block">
            <%= link_to "Log Out", destroy_admin_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item d-none d-md-block">
            <%= link_to "Login", new_admin_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
        <!-- mobile view -->
        <% if admin_user_signed_in? %>
          <li class="nav-item d-md-none">
            <%= link_to current_admin_user.email, root_path, class: "nav-link" %>
          </li>
          <li class="nav-item d-md-none">
            <%= link_to "Log Out", destroy_admin_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item d-md-none">
            <%= link_to "Login", new_admin_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item d-md-none">
            <%= link_to "Sign Up", root_path, class: "nav-link" %>
          </li>
         <% end %>
      </ul>
      <!-- Links -->

    </div>
    <!-- Collapsible content -->

  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <em class="nav-link"></em>
    </li>
  </ul>

  <!-- <ul class="navbar-nav ml-auto">
    <li class="nav-item d-none d-sm-inline-block">
      <a href="index3.html" class="nav-link">Home</a>
    </li>
    <li class="nav-item">
      <div class="theme-switch-wrapper nav-link">
        <label class="theme-switch" for="checkbox">
          <input type="checkbox" id="checkbox" />
          <span class="slider round"></span>
        </label>
      </div>
    </li>
    <li class="nav-item">
      <em class="nav-link">Enable Dark Mode!</em>
    </li>
  </ul> -->

  <!-- SEARCH FORM -->
  <!-- <form class="form-check-inline ml-3">
    <div class="input-group input-group-sm">
      <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
      <div class="input-group-append">
        <button class="btn btn-navbar" type="submit">
          <i class="fa fa-search"></i>
        </button>
      </div>
    </div>
  </form> -->
</nav>

app/views/shared/admin/_sidebar.html.erb
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo  -->
  <!--
  <a href="index3.html" class="brand-link">
    <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-light">AdminLTE 3</span>
  </a> -->

  <a href="<%= admin_root_path %>" class="brand-link">
    <span class="brand-icon">
      <i class="fas fa-utensils"></i>
    </span>
    <span class="brand-text font-weight-light">Joyful</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <!--
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
            <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
            <a href="#" class="d-block">Alexander Pierce</a>
        </div>
    </div>
    -->

    <!-- <div class="form-inline mt-2">
    <div class="input-group" data-widget="sidebar-search">
      <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
      <div class="input-group-append">
        <button class="btn btn-sidebar">
          <i class="fas fa-search fa-fw"></i>
        </button>
      </div>
    </div><div class="sidebar-search-results"><div class="list-group"><a href="#" class="list-group-item"><div class="search-title"><strong class="text-light"></strong>N<strong class="text-light"></strong>o<strong class="text-light"></strong> <strong class="text-light"></strong>e<strong class="text-light"></strong>l<strong class="text-light"></strong>e<strong class="text-light"></strong>m<strong class="text-light"></strong>e<strong class="text-light"></strong>n<strong class="text-light"></strong>t<strong class="text-light"></strong> <strong class="text-light"></strong>f<strong class="text-light"></strong>o<strong class="text-light"></strong>u<strong class="text-light"></strong>n<strong class="text-light"></strong>d<strong class="text-light"></strong>!<strong class="text-light"></strong></div><div class="search-path"></div></a></div></div>
  </div> -->

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview" role="menu">
        <!-- Add icons to the links using the .nav-icon class
        with font-awesome or any other icon font library -->
        <li class="nav-item">
          <a href="<%= admin_notice_path %>" class="nav-link">
            <i class="far fa-bell nav-icon"></i>
            <p>
              Notifications
            </p>
          </a>
        </li>

        <li class="nav-item">
          <a href="<%= admin_dish_groups_path %>" class="nav-link">
            <i class="nav-icon fas fa-images"></i>
            <p>
              Dish Groups
            </p>
          </a>
        </li>

        <li class="nav-item has-treeview">
          <a href="#" class="nav-link treeview-link">
            <i class="nav-icon fas fa-utensils"></i>
            <p>
              Menu
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview" style="display: none;">
            <% DishGroup.order(position: :asc).pluck(:group_type, :name).each do |group_type, name| %>
              <li class="nav-item">
                <a href="<%= admin_dishes_path(group_type: group_type) %>" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p><%= name || group_type.titleize %></p>
                </a>
              </li>
            <% end %>
          </ul>
        </li>

        <!-- Nested Link -->
        <!--
        <li class="nav-item has-treeview">
          <a href="#" class="nav-link treeview-link">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
              11111
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview" style="display: none;">
            <li class="nav-item">
              <a href="<%= admin_dishes_path(dish_type: 'chicken') %>" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Dashboard v3</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="<%= admin_dishes_path(dish_type: 'beef') %>" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Dashboard v3</p>
              </a>
            </li>
          </ul>
        </li>
        -->

        <!-- Simple Link -->
        <!--
        <li class="nav-item">
          <a href="<%= admin_dishes_path(dish_type: 'beef') %>" class="nav-link">
            <i class="nav-icon fas fa-th"></i>
            <p>
              Simple Link
              <span class="right badge badge-danger">New</span>
            </p>
          </a>
        </li>
        -->

        <li class="nav-item">
          <a href="<%= admin_dashboard_edit_background_images_path %>" class="nav-link">
            <i class="nav-icon fas fa-cog"></i>
            <p>
              Settings
            </p>
          </a>
        </li>

      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

<script>
  let url = window.location.href;

  // show sidebar by url
  $(function($) {
    $('.nav li a').each(function() {
      if (this.href === url) {
        $(this).closest('a').addClass('active');
        $(this).parents('.has-treeview').addClass('menu-is-opening');
        $(this).parents('.has-treeview').addClass('menu-open');
        $(this).parents('.has-treeview').find('.treeview-link').addClass('active');
        $(this).parents('.nav-treeview').show();
      }
    });
  });

  // click sidebar link
  $('.nav li a').click(function(){
    $('.nav li a').removeClass('active');
    $('.nav li a').each(function() {
      if (this.href === url) {
        $(this).closest('a').addClass('active');
        $(this).parents('.has-treeview').find('.treeview-link').addClass('active');
      }
    });
  })
</script>